name: Crowdin Synchronization

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        with:
          upload_sources: true      # Upload source files to Crowdin
          download_translations: true # Download translated files from Crowdin
          config: './crowdin.yml'    # Path to Crowdin configuration file
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
